### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by jgarackal** [NodeRedis/node-redis-parser#16]
There is some parsing issue which has started causing the following error since the new release:

`
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod (/var/app/current/node_modules/newrelic/lib/shimmer.js:246:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/app/current/node_modules/redis/node_modules/redis-parser/index.js:3:18)
    at Module._compile (module.js:460:26)
/var/app/current/node_modules/redis/node_modules/redis-parser/lib/parser.js:230
      const err = new ReplyError('Protocol error, got ' + JSON.stringify(Strin
`

**Comment by bradmurray** [comment]
It looks like line 230 of /lib/parser.js has to change from
```javascript
const err = new ReplyError('Protocol error, got ' + JSON.stringify(String.fromCharCode(type)) + ' as reply type byte', 20)
```
to
```javascript
var err = new ReplyError('Protocol error, got ' + JSON.stringify(String.fromCharCode(type)) + ' as reply type byte', 20)
```

**Comment by barn3y** [comment]
I reported the same issue in #17...

I suspect the use of `const` with `"use strict";` in node 0.10 or 0.12 is the root cause. Hopefully either `const` can be replaced with `var`, or the minimum engine requirement can be bumped to node 4.0.

**Comment by BridgeAR** [comment]
Fixed
