### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by barn3y** [NodeRedis/node-redis-parser#17]
Hi, we're still running some legacy code on node 0.10, a recent change has caused our services to fail with:

```
.../node_modules/redis/node_modules/redis-parser/lib/parser.js:230 const err = new ReplyError('Protocol error, got ' + JSON.stringify(Strin
     ^^^^^
SyntaxError: Use of const in strict mode.
 at Module._compile (module.js:439:25)
 at Object.Module._extensions..js (module.js:474:10)
```

using `const` with `"use strict";` fails in node 0.10 / 0.12, yet node-parser's package.json still lists the minimum engine as node 0.10.

the crashing line was introduced in:

https://github.com/NodeRedis/node-redis-parser/commit/6c149eafebd945ba66047ea771b265139386ce16#diff-3fab227e34d65fe9bb2d6ea53eec41cfR226

Could `const` either be removed, or the minimum engine requirements updated?

**Comment by barn3y** [comment]
Whoops, this is a dupe of #16, closing.
