### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by boughtonp** [NodeRedis/node-redis-parser#54]
Every now and then the error below occurs and crashes Node.
The specific circumstances which trigger it are unknown.

```
/opt/nodeapp/node_modules/redis-parser/lib/parser.js:560
  while (this.offset < this.buffer.length) {
                                   ^

TypeError: Cannot read property 'length' of null
    at JavascriptRedisParser.execute (/opt/nodeapp/node_modules/redis-parser/lib/parser.js:560:36)
    at Socket.<anonymous> (/opt/nodeapp/node_modules/redis/index.js:274:27)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

Running node-redis 2.8.0 and thus node-redis-parser 2.6.0 on Node v8.8.1, AWS Linux

I see there's a node-redis-parser v3.0.0 which has made changes that may or not effect this error, but no updated version of node-redis to use it?

**Comment by Rixoro** [comment]
Any updates or status on this? This is currently affecting a project I am working on
