### ISSUE TITLE
ERR invalid expire time in set

### ISSUE THREAD

**Issue by ShalaQweghen** [NodeRedis/node-redis-parser#63]
Hello,

I have a Node.js web application which uses redis as session storage. Some requests receive the following ReplyError while trying to save the session:

```
ReplyError: ERR invalid expire time in set
   at parseError (.../node_modules/redis-parser/lib/parser.js:179:12)
   at parseType (.../node_modules/redis-parser/lib/parser.js:302:14)
```

I checked the specified file but I couldn't find anything which might cause it. Also, as far as I know, `set` method doesn't receive a expire time argument. I would very much appreciate any pointers as to how to fix it or what may cause it.

OS: `Ubuntu 18.04.1 LTS`
NodeJS version: `12.19.0`
redis-server version: `4.0.9`
node-redis version: `3.0.2`
node-redis-parser version: `3.0.0`

**Comment by ShalaQweghen** [comment]
I noticed that this belongs to the connect-redis repository. Sorry for reopenning the issue.
