### ISSUE TITLE
ParserError: Protocol error, got "\r" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by LimitedHype** [NodeRedis/node-redis-parser#64]
node:events:368
      throw er; // Unhandled 'error' event
      ^

ParserError: Protocol error, got "\r" as reply type byte. Please report this.
    at handleError (/Users/xxxx/xxxx/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/Users/xxxx/xxxx/node_modules/redis-parser/lib/parser.js:304:14)
Emitted 'error' event on RedisClient instance at:
    at JavascriptRedisParser.returnFatalError (/Users/xxxx/xxxx/node_modules/redis/index.js:156:18)
    at handleError (/Users/xxxx/xxxx/node_modules/redis-parser/lib/parser.js:196:10)
    at parseType (/Users/xxxx/xxxx/node_modules/redis-parser/lib/parser.js:304:14)
    at JavascriptRedisParser.execute (/Users/xxxx/xxxx/node_modules/redis-parser/lib/parser.js:533:24)
    at Socket.<anonymous> (/Users/xxxx/xxxx/node_modules/redis/index.js:219:27)

**Comment by hunkydoryrepair** [comment]
I've received this error:

`ParserError: Protocol error, got "Ã" as reply type byte. Please report this.`

but it is 1 in a billion. could be a legitimate network corruption or bug in the redis server?

**Comment by JClackett** [comment]
any ideas?? getting blasted by this
